name: push 기반 CI/CD 테스트

# 트리거 지정, CI/CD가 작동하게 되는 원인, 이벤트등 정의
# main 브랜치에서 push 이벤트(리슨 -> on)가 발생되면 아래 설정한 내용 작동한다

on:
  push:
    branches:
      - main

# 개별작업(jobs)을 순서대로 나열 (파이프라인)
jobs:
  # ci 라는 작업을 하나 설정
  ci:
    # 어떤 OS에서 작업을 진행할것인가? -> github에서 클라우드 방식으로 제공 (내부적)
    runs-on: ubuntu-latest

    # 작업단계 지정
    steps:
      # 1. github에 저장되어 있는 최신내용을 체크아웃 (소스를 모두 내려받음)
      - name: 코드 checkout
        uses: actions/checkout@v3

      # 환경변수 (생략)
      # 확인 or 단위 테스트(생략)
      - name: 확인 검증
        # 여러 명령어는 |  <- 사용함
        run:  |
          pwd
          ls -al
          cat main.py
        shell: bash
      
      # CI쪽 서버에서 EC2 서버(배포용 서버)로 배포 -> SSH
      # 사전 -> aws에서 ec2 하나 생성 -> ip/domain, ubuntu(사용자명), key는 pem파일
      #     -> github 상 해당 저장소에 secrets 변수로 위의3개 값을 세팅
      # EC2 서버의 SSH 인바운드의 접근 제약 정보에서 특정 IP가 아닌 어느곳애서도 접근 가능하게 구성
      # 0.0.0.0/0 그럼 보안은...???
      - name: sourcecode copy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          # 복사할 대상
          source: .
          # ubuntu os가 세팅된 ec2 서버의 /home/ubuntu/projects/*.* 복사
          target: "/home/ubuntu/projects"
        
      - name: run Script And Service restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          scripts: |
            #cd /home/ubuntu/projects
            #./web/bin/pip install -r requirements.txt
            sudo systemctl restart hello.service